apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: iot-pong-proj
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: The mightful iot-pong
  sourceRepos:
  - '*' 
  destinations:
  - namespace: dev
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace