global:
  edition: ce
  hosts:
    https: false
    externalIP: 0.0.0.0
    domain: iot.dev
  kas:
    enabled: false
  registry:
    enabled: false
  ingress:
    enabled: false
    configureCertmanager: false
  certmanager:
    enabled: false
  gitlab-runner:
    install: false
nginx-ingress:
  enabled: false