Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  config.vm.define "plouvelS" do |machine|
    machine.vm.hostname = "plouvelSW"
    machine.vm.network "private_network", ip: "192.168.56.110"

    machine.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 1024
      libvirt.title = "plouvelS"
      libvirt.description = "K3S Server"
    end

    machine.vm.provision "ansible" do |ansible|
        ansible.verbose = "v"
        ansible.playbook = "scripts/provision.yml"
    end
  end
end