Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "generic/alpine316"

  config.vm.define "plouvelS" do |serv|
    serv.vm.hostname = "plouvelS"
    serv.vm.network "private_network", ip: "192.168.56.110"

    serv.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 1024
      libvirt.title = "plouvelS"
      libvirt.description = "K3S Server"
    end

    serv.vm.provision "shell", path: "scripts/bootstrap_server.sh"
  end

  config.vm.define "plouvelSW" do |worker|
    worker.vm.hostname = "plouvelSW"
    worker.vm.network "private_network", ip: "192.168.56.111"

    worker.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 1024
      libvirt.title = "plouvelSW"
      libvirt.description = "K3S Agent"
    end

    worker.vm.provision "shell", path: "scripts/bootstrap_worker.sh"
  end
end
