Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"

  def configure_vm(vm, name, ip, description)
    vm.vm.hostname = name
    vm.vm.network "private_network", ip: ip

    vm.vm.provider "libvirt" do |libvirt|
      libvirt.cpus = 2
      libvirt.memory = 1024
      libvirt.title = name
      libvirt.description = description
    end

    vm.vm.provision "ansible" do |ansible|
      ansible.verbose = "v"
      ansible.playbook = "scripts/provision.yml"
      ansible.groups = {
        "master" => ["plouvelS"],
        "worker" => ["plouvelSW"],
        "all:vars" => {
          "ansible_python_interpreter" => "/usr/bin/python3"
        }
      }
    end
  end

  config.vm.define "plouvelS" do |serv|
    configure_vm(serv, "plouvelS", "192.168.56.110", "K3S Server")
  end

  config.vm.define "plouvelSW" do |worker|
    configure_vm(worker, "plouvelSW", "192.168.56.111", "K3S Agent")
  end
end
