- name: Install and Configure Gitlab
  hosts: all
  gather_facts: true
  tasks:
    - name: Install Prerequisites
      become: true
      ansible.builtin.apt:
        name:
          - curl
          - openssh-server
          - ca-certificates
          - perl
        update_cache: true
        state: present
    - name: Fetch Debian Script
      ansible.builtin.get_url:
        url: "https://packages.gitlab.com/install/repositories/gitlab/gitlab-ce/script.deb.sh"
        dest: /tmp/gitlab-ce-deb.sh
        mode: a+r
    - name: Run Debian Script
      become: true
      ansible.builtin.command:
        cmd: /bin/bash /tmp/gitlab-ce-deb.sh
        creates: /etc/apt/sources.list.d/gitlab_gitlab-ce.list
    - name: Install Gitlab-CE
      # For more informations, see : https://docs.gitlab.com/omnibus/settings/configuration.html
      become: true
      environment:
        EXTERNAL_URL: "{{ gitlab_external_url }}"
        # https://docs.gitlab.com/omnibus/installation/index.html#set-up-the-initial-account
        GITLAB_ROOT_EMAIL: "{{ gitlab_root_email }}"
        GITLAB_ROOT_PASSWORD: "{{ gitlab_root_password }}"
      ansible.builtin.apt:
        name: gitlab-ce
        update_cache: true
        state: present
