- name: Fix DNS failure on Debian 12 at 42
  hosts: all
  tasks:
    - name: Install resolvconf, if not present
      ansible.builtin.apt:
        name: resolvconf
        state: present
    - name: Start resolvconf, if not started
      ansible.builtin.service:
        name: resolvconf
        state: started
    - name: Update resolvconf head
      become: true
      ansible.builtin.lineinfile:
        path: /etc/resolvconf/resolv.conf.d/head
        line: nameserver 8.8.8.8
        insertafter: EOF
        state: present
    - name: Update resolvconf
      become: true
      ansible.builtin.shell:
        cmd: resolvconf -u

- name: Setup K3S Master Node
  hosts: all
  vars:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
  gather_facts: true
  tasks:
    - name: Get services facts
      ansible.builtin.service_facts:
    - name: Install K3S, if not installed
      become: false
      ansible.builtin.shell:
        cmd: curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --write-kubeconfig-mode 644 --flannel-iface eth1" sh -s -
      when: ansible_facts.services['k3s.service'] is not defined
    - name: Install pip
      become: true
      ansible.builtin.apt:
        name: python3-pip
        update_cache: true
        state: present
    - name: Install ansible K8S module prerequisites
      ansible.builtin.pip:
        name:
          - openshift
          - pyyaml
          - kubernetes
        break_system_packages: true
        state: present
    - name: Copy configurations
      ansible.builtin.copy:
        src: ../confs
        dest: /home/vagrant/confs
    - name: Apply deployments
      kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /home/vagrant/confs/deployments.yaml
    - name: Apply services
      kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /home/vagrant/confs/services.yaml
    - name: Apply ingress
      kubernetes.core.k8s:
        state: present
        kubeconfig: /etc/rancher/k3s/k3s.yaml
        src: /home/vagrant/confs/ingress.yaml
